/* Generated By:JavaCC: Do not edit this line. AssignmentConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AssignmentConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int I_SEE = 5;
  /** RegularExpression Id. */
  int THE = 6;
  /** RegularExpression Id. */
  int IS = 7;
  /** RegularExpression Id. */
  int ARE = 8;
  /** RegularExpression Id. */
  int NORTH = 9;
  /** RegularExpression Id. */
  int EAST = 10;
  /** RegularExpression Id. */
  int SOUTH = 11;
  /** RegularExpression Id. */
  int WEST = 12;
  /** RegularExpression Id. */
  int SEMI_COLON = 13;
  /** RegularExpression Id. */
  int FULL_STOP = 14;
  /** RegularExpression Id. */
  int CONNECTIVE = 15;
  /** RegularExpression Id. */
  int NUMBER = 16;
  /** RegularExpression Id. */
  int UNIT = 17;
  /** RegularExpression Id. */
  int LBRACE = 18;
  /** RegularExpression Id. */
  int LOCATION_PART = 19;
  /** RegularExpression Id. */
  int RBRACE = 20;

  /** Lexical state. */
  int LOCATION_STATE = 0;
  /** Lexical state. */
  int DEFAULT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"I See\"",
    "\"The\"",
    "\"is\"",
    "\"are\"",
    "\"north of\"",
    "\"east of\"",
    "\"south of\"",
    "\"west of\"",
    "\";\"",
    "\".\"",
    "<CONNECTIVE>",
    "<NUMBER>",
    "<UNIT>",
    "\"[\"",
    "<LOCATION_PART>",
    "\"]\"",
  };

}
